apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chat-application
  description: Angular chat application
  annotations:
    github.com/project-slug: udhayakiran-stack/chatApplication
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: development
  owner: guests